# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d715a010f50de46fd01b199c8e2e2fe73c7f8060c643bed8a070dd11f0884fa794abb088200a6b749b777d31dbc762684a1ffa4c569faea3f03c6f57b5dca8

test:
  secret_key_base: 649bef5c725fa2157ff040faee98f8198d98c3aab6b8a428919ed5d5ae90e74b21da686c045fa99477d4e1b59f5cae1b668c75cad4f6963374911c77542b6008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
